appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Zvwvx0+HZTBJO8acnVBtR1MRkj3fAObd3awFr9hR6KWcMH+ohIXPElGqvrHKQlm1ZRId2kuoLiDkRmtH32JJ6L05v8PM5eyeY114AVV6ywId/xW0kzbiB9bKwAjwAGCJ0Kcy4o0GhE3Uus1ev8YthsVfVl7kJKhpjKfOqzCyZpqJ4QbLRxTv2Nu7lG82+32Artf7CIizsVm0OSyqqmndgmQ2yXunJ4BWLfFVXpm9EC6VRby+jHcNv4nqV1zAEwm8UxAnWOmKcwltLZhf0tIso9Hk24forle7dfZUpBzwhI33dEYEc9z2J2+RD2s0+8q4j9W4iiSAfaHQjARt1t/ZlNMGkiNrOO6ON4TJsoZGk401ZQSE7P8NzyH1GcG7XNPMjAoRhI5AJSvALBQhnFYqJ5d6ROfkfl/yMBQRbtR6VkNGjdI/n4DU8CAk1mNbFqI8Xp7QK9J0f3FYhPYd3e6llNNxowpfE6pFEcBzq7SXyZeEPbQUUFY0mspEmogcHFseAyfmv3Smc/6eUYU7zS6I2/7jD1mPhtMbfRAivfuB3PE71sjY7PKvIVf/ilwY2cH2dwRK/ROzx1SNYeKFqgTy84YBV0L93tQiHqA6c8lOiEDO+g5AKyBmURIVUkD3LKLwBiQNvjqokEKu5XFwWkbvHdIhm/IwngIbYer/aT4DcjA=}
