travis:
  secure:
    BINSTAR_TOKEN: lS/WczDJKJI5X7pkUPMxvn33ad1N+Y6QcTVR4/Ir1KOEzRAW9bqSRqe+oyH4/29HiVZVjoHNd8RZ+3Y13Uj+47lD6nhUjntqXzRq+B8OG3WkOMmTq6/2vRpytzBuwk3k1q0gdUutasU04p37CQtVY6bPHMAUsudDhQXJvRONTKDbELuAzd9HBoMTCjWBwOgQ02Kw4eMioTF4MpxN4C2sweorwPnoo+ZY61fbBA9P7ZA1D7Vx7FYfONQY063bSvUPN7qITh61+RsdHCQvHUPVCgK6d/mCpoP/DBNDenprRL3hQsopE2aLh0GTLayBloidK8BidhbN/3b9P4CKOdak9VNCEPJ4LpKOPWflqG41PCfbriSTacIKY/EkcF/hQnItTP0/efmgZ19sQZACNdUFsvNpwxTTYOZzQ0IF6zeaw6AdYUBD+s57f9XgwTsTvU+s4sFY+mJEUy73t1HsqTWpyMBCOAUmRGL9MVAMgkt0zNgOcIYx2j9cT80sDJEueO11JSiT4c+VSOrQ7Htl4JMIWGcuVVM84wXEnyucfzufRQzlcew24DKrFUeN88SBkUGEblwmjYo0FO9qRNuG21fuMnNgrqN/fm0K797COcKBQ2zQo+Pil8Hd424MULoSJknokz9MptFBZdB0YZuyce9+dUMhN1sTF906+ZtscpClLfw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
